# Generated by Django 6.0.7 on 2026-07-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
