# Generated by Django 6.0.7 on 2026-07-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
